# Generated by Django 3.2.9 on 2021-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('days', models.IntegerField(verbose_name='Days')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
    ]
